CREATE SEQUENCE team_seq START WITH 10;
CREATE SEQUENCE championship_seq START WITH 10;
CREATE SEQUENCE people_seq START WITH 25;
CREATE SEQUENCE stat_seq START WITH 25;
CREATE SEQUENCE match_seq START WITH 1;
